app:
  image: ndzenyuy/lumia-app:latest
  replicas: 2
  port: 8080

db:
  image: ndzenyuy/lumia-db:latest
  port: 3306
  name: accounts
  user: admin
  password: YWRtaW4xMjM=
  storage: 3Gi
  storageClass: gp2
  replicas: 1

ingress:
  host: www.app.conceptix-art.com
  className: nginx
